### ISSUE TITLE
DHT providing never finishes

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p-pubsub-router#32] opened 2019-06-10 20:55 UTC
It uses a context with no deadline, which does not operate well with DHT providing:

```
goroutine 13313 [9m0s]:
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).Provide [0xc0001888f0, 0x1a534a0, 0xc0151884c0, 0xc002cf0ed0, 0x24, 0xc0003d2601, 0x0, 0x0]
	/root/gopath/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.1.1-0.20190607150147-25009616a4d5/routing.go:422
github.com/libp2p/go-libp2p-pubsub-router.bootstrapPubsub.func1 [0x7f2feb060d90, 0xc0001888f0, 0x1a534a0, 0xc0151884c0, 0xc002cf0ed0, 0x24, 0xc0181b8f50, 0x47]
	/root/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub-router@v0.1.0/pubsub.go:338
created by github.com/libp2p/go-libp2p-pubsub-router.bootstrapPubsub []
	/root/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub-router@v0.1.0/pubsub.go:337
```

**Comment by aschmahmann** [comment] 2019-06-12 03:51
@raulk this is the same issue as #28 which we mostly plan to solve by landing libp2p/go-libp2p-pubsub#184.

Unfortunately, `PubSub.Publish()` does not take a context which means to some degree this problem will still exist until we either A) give Publish a context, or B) allow Publish (at either the PubSub or floodsub/gossipsub layer) to store a backlog of messages to be sent once bootstrapping has completed and we've found peers.

If we land libp2p/go-libp2p-pubsub#184 without solving the above we can easily just wrap the `Publish` with a goroutine + context to make sure that we respect the context of `PutValue`.

**Comment by aschmahmann** [comment] 2019-07-03 13:57
@raulk I'm going to close this as a duplicate of #28. Feel free to reopen if you feel this is a different issue.

**Closed by aschmahmann** 2019-07-03 13:57 UTC
